// Generated by CoffeeScript 1.8.0
(function() {
  var app, chat, http, io;

  app = require('express')();

  http = require('http').Server(app);

  io = require('socket.io')(http);

  app.get('/', function(req, res) {
    return res.sendFile(__dirname + '/index.html');
  });

  chat = io.of('/chat').on('connection', function(socket) {
    console.log(socket.id + "connect");
    socket.emit('welcome', 'Hello');
    return socket.on('disconnect', function() {
      return console.log('user disconnected');
    });
  });

  setTimeout(function() {
    return chat.emit('a message', "setTimeout");
  }, 5000);

  http.listen(3002, function() {
    return console.log('listening on *:3002');
  });

}).call(this);

//# sourceMappingURL=app.js.map
