// Generated by CoffeeScript 1.8.0
(function() {
  var socket;

  socket = io('http://localhost:3002');

  socket.on('chat message', function(msg) {
    return console.log(msg);
  });

  socket.on('welcome', function(msg, t) {
    var options;
    options = {
      type: "basic",
      title: "链接通知",
      message: "已链接到socket：" + msg,
      iconUrl: 'images/1.png'
    };
    chrome.notifications.create("123", options, function(test) {
      return console.log("test", test);
    });
    return console.log(msg, t);
  });

}).call(this);

//# sourceMappingURL=app.js.map
